Vagrant.configure("2") do |config|
  # Use the box you just downloaded
  config.vm.box = "bento/ubuntu-22.04"

  # Changed host port to 8888 because 8080 is already in use
  config.vm.network "forwarded_port", guest: 80, host: 8888

  # Automated Nginx Installation
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx
    echo "<h1>Vagrant Provisioning Success: Nginx is running in VirtualBox</h1>" > /var/www/html/index.html
  SHELL

  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "Boris_Vagrant_Lab"
  end
end
